
name: CI/CD - Spring Boot na OCIR

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
  OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
  OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
  OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
  OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
  OCIR_NAMESPACE: ${{ secrets.OCIR_NAMESPACE }}

  OCIR_REGION_KEY: fra
  OCIR_REPO: spring-projects/spring-boot-hello-app
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: oracle
          java-version: "17"

      - name: Build i test
        run: ./mvnw -B clean package -DskipTests

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: jar
          path: target/*.jar

      - name: Login to OCIR
        if: github.event_name == 'push'
        uses: oracle-actions/login-ocir@v1.3.0
        with:
          auth_token: ${{ secrets.OCI_AUTH_TOKEN }}

      - name: Build Docker image
        if: github.event_name == 'push'
        run: |
          IMAGE="${OCIR_REGION_KEY}.ocir.io/${OCIR_NAMESPACE}/${OCIR_REPO}"

          docker build -t "$IMAGE:${IMAGE_TAG}" -t "$IMAGE:latest" .

      - name: Push Docker image
        if: github.event_name == 'push'
        run: |
          IMAGE="${OCIR_REGION_KEY}.ocir.io/${OCIR_NAMESPACE}/${OCIR_REPO}"

          docker push "$IMAGE:${IMAGE_TAG}"
          docker push "$IMAGE:latest"
